### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by lockie** [msys2/msys2-docker#7]
Hey! Thanks for this project, it's been a great boon and helped me to significantly simplify [my CI](https://gitlab.com/lockie/docker-lisp-gamedev/-/commit/43280b2699d18c32d779ef19e779d50c60dcfe8f).
Do you mind adding license, copyrights and all that stuff to this project, so I can properly reference it in my readme? 🙂

**Comment by Kreijstal** [comment]
> Hey! Thanks for this project, it's been a great boon and helped me to significantly simplify [my CI](https://gitlab.com/lockie/docker-lisp-gamedev/-/commit/43280b2699d18c32d779ef19e779d50c60dcfe8f). Do you mind adding license, copyrights and all that stuff to this project, so I can properly reference it in my readme? 🙂

Genius, the license is probably the same as msys2 license, the same as cygwin license

**Comment by lazka** [comment]
The initial Dockerfile wased base on https://github.com/pojntfx/hydrapp/blob/main/hydrapp/pkg/builders/msi/Dockerfile as pointed out in the README which is Apache-2.0. I'd argue things have changed enough since then that it's no longer relevant copyright wise.

I guess BSD-3 like the rest would be OK?

**Comment by lockie** [comment]
Awesome, thanks!
